drugtypes = {
    "Stimulant": [
        "4F-MPH",
        "3-MMC",
        "4-MMC",
        "2-FEA",
        "2-FA",
        "3-FA",
        "4-FA",
        "A-PVP",
        "Hexen",
        "MDPV",
        "4-FMA",
        "2C-H",
        "4-MEC",
        "NEP",
        "Prolintane",
        "Adrafinil",
        "5-MeO-MiPT",
    ],
    "Psychedelic": [
        "LSD-25",
        "1P-LSD",
        "Mushroom",
        "4-ACO-DMT",
        "2-CB",
        "4-HO-MET",
        "DMT",
        "Mescaline",
        "Ayahuasca",
        "LSA",
        "1cP-LSD",
        "AL-LAD",
        "ALD-52",
        "ETH-LAD",
        "LSZ",
        "1B-LSD",
        "5-MeO-DMT",
        "Allylescaline",
        "DOB",
        "MAL",
        "25I-NBOMe",
        "25I-NBOh",
        "25C-NBOMe",
    ],
    "Opioid": [
        "O-DSMT",
        "Tramadol",
        "Kratom",
        "Etazene",
        "Etonitazepipne",
        "Metazene",
        "Protonitazene"
        "Oxycodone",
        "Hydrocodone",
        "Metonitazene"
    ],
    "Depressant": [
        "Xanax",
        "Cannabis",
        "Bromazolam",
        "Clonazolam",
        "Etizolam",
        "Phenibut",
        "Klonopin",
        "BDO",
    ],
    "Dissociative": ["2F-DCK", "DCK", "FXE", "3-HO-PCP", "3-MEO-PCP", "MXE", "O-PCE"],
    "Empathogen": ["MDMA", "5-MAPB", "6-APB"],
    "Deliriant": ["Salvia"],
}
